# ===============================
# CONFIGURACION BASE DE DATOS
# ===============================

spring.datasource.url=jdbc:mysql://localhost:${DB_PORT:3306}/banco_xyz_batch?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:NuevaClave123!}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# CONFIGURACION JPA
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===============================
# CONFIGURACION SPRING BATCH
# ===============================

spring.batch.jdbc.initialize-schema=always
spring.batch.job.enabled=false

# ===============================
# PARAMETROS DE RENDIMIENTO BATCH
# ===============================

batch.chunk-size=5
batch.threads.core=5
batch.threads.max=5
batch.queue-capacity=15
batch.skip-limit=60
batch.retry-limit=3